title: <p align="center"> Pushkar Verma </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/pushkar-verma-974a4a168/">LinkedIn</a> |
  <a href="https://github.com/Pushkarkv">GitHub</a>
  
  <br>  
  Seasoned Data Scientist experienced working with large & complex datasets,
  building scalable & efficient data pipelines and building robust 
  Machine Learning and Analytical Models to solve complex business concerns.
  Bringing 2 years of related experience and 3 plus years of overall experience.
  <br>
  </p>



theme: jekyll-theme-minimal
